[FEATURE] 과목들의 수강신청 당시 empty seat 정보를 알 수 있도록 그래프 추가
gsainfoteam/gist-lecture-searcher pull request #1
Opened 2024-02-17 04:09 UTC by MiRoro2

- 현재 수집한 데이터는 2023-fall, 2024-spring이 있습니다
- 일단 과목 이름을 클릭하면 열 수 있도록 해놓았습니다
- 수집한 데이터 중에 없는 과목은 그래프가 안 열립니다
- recharts로 구현하였고, 이런 식으로 수강신청 당시 시간 당 count 현황이 어땠는지를 보여주게 됩니다

<img width="969" alt="스크린샷 2024-02-17 오후 1 09 05" src="https://github.com/gsainfoteam/gist-lecture-searcher/assets/57053429/1b99d0ea-f639-455d-983c-0447f571060f">

2024-02-18 04:54 UTC, 2paperstar requested changes

2024-02-18 04:54 UTC, 2paperstar commented on .gitignore
> +.env.development
.env.development를 쓰지 말고, .env.development.local을 사용해주세요

2024-02-18 07:35 UTC, MiRoro2 commented on .gitignore
> +.env.development
아하

2024-02-18 18:00 UTC, 2paperstar commented on src/app/components/Lectures/Inner.tsx
> +      return null;
🤔 왜 이 로직이 마음에 안 들지,, 오브젝트로 묶어서 처리하면 좋을 것 같은 느낌?

2024-02-18 18:00 UTC, 2paperstar commented on src/app/components/Lectures/Inner.tsx
> +      : null;
이게 되는군욥..
API를 만들어두는건 어때요?

2024-02-18 18:00 UTC, 2paperstar commented
수강신청 시간을 절대적으로 표시하지 말고 상대적으로 (e.g. +02:35) 표시하면 좋겠어요

2024-02-19 00:37 UTC, 2paperstar approved these changes
자꾸 블록 해두면 안 될 것 같아서 일단 머지하고 나중에 제가 PR 올리던지? 그렇게 해볼게요

2024-02-19 01:44 UTC, MiRoro2 commented on src/app/components/Lectures/Inner.tsx
> +      return null;
좀더 클린하게 가려면 그게 맞긴 하겠지
그렇게 고쳐볼게

2024-02-19 01:48 UTC, MiRoro2 commented on src/app/components/Lectures/Inner.tsx
> +      : null;
맨 처음에 public에 static json 파일을 넣어놓고 api로 불러오려 했었는데 그건 안되더라구요..?? 경로를 잘못 지정해서 그런가
아니면 이거 불러오는 로직을 다른 코드로 빼라는 말씀이신가요

2024-02-19 01:50 UTC, 2paperstar commented on src/app/components/Lectures/Inner.tsx
> +      : null;
src/app/api 안쪽에 라우터 만들어서 불러올 수 있게끔이용

2024-02-19 01:50 UTC, MiRoro2 commented
> 수강신청 시간을 절대적으로 표시하지 말고 상대적으로 (e.g. +02:35) 표시하면 좋겠어요

이거는 제가 json 데이터에서 그렇게 바꾸면 될것같아요

2024-02-19 01:57 UTC, MiRoro2 commented on src/app/components/Lectures/Inner.tsx
> +      : null;
아하.. 거기서 따로 json을 리턴해주는 api를 만든다는 말씀이시군요
혹시 그렇게 하는 이유가 있을까요?? 좀 더 클린해서 그런가

2024-02-19 01:59 UTC, 2paperstar commented on src/app/components/Lectures/Inner.tsx
> +      : null;
사실 이거의 본 목적은 json 전체를 다 리턴하지말고 보고 있는 강좌의 데이터만 뿌려줄 수 있게끔 수정하는거였어요

2024-02-19 02:01 UTC, crown-3 commented on src/app/components/Lectures/Inner.tsx
> +      : null;
아아 하긴 지금은 저 겁나큰 데이터를 다 리턴해서.. 알겠습니다 이것도 한번 고쳐볼게요

2024-02-20 12:59 UTC, merged